=== DanPhillips888/WorldHeritage/DataRaw/WHSite.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="WHSite" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="WHSite">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="HeritageWHSite" index-key="UNESCO " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="NatSiteID" index-key="UNESCO " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="UNESCO Nation Site " primary="yes" unique="yes" clustered="no" order="asc asc asc"/>
<od:index index-name="SiteWHSite" index-key="Site Nation " primary="no" unique="no" clustered="no" order="asc asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="jMYRyFtcd0id1BGLfo17yQ==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="UNESCO" minOccurs="0" od:jetType="integer" od:sqlSType="smallint" type="xsd:short">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="630"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Nation" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="765"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="3"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Site" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2340"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Seen" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="645"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== DanPhillips888/WorldHeritage/DataRaw/WHSite.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="WHSite.xsd" generated="2022-07-05T17:14:38">
<WHSite>
<UNESCO>1</UNESCO>
<Nation>ECU</Nation>
<Site>Galapagos</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>2</UNESCO>
<Nation>ECU</Nation>
<Site>Quito</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>3</UNESCO>
<Nation>GER</Nation>
<Site>Aachen</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>4</UNESCO>
<Nation>CAN</Nation>
<Site>L’Anse aux Meadows</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>8</UNESCO>
<Nation>TUN</Nation>
<Site>Ichkeul</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>9</UNESCO>
<Nation>ETH</Nation>
<Site>Simien</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>10</UNESCO>
<Nation>ETH</Nation>
<Site>Awash Valley</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>12</UNESCO>
<Nation>ETH</Nation>
<Site>Tiya</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>15</UNESCO>
<Nation>ETH</Nation>
<Site>Aksum</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>17</UNESCO>
<Nation>ETH</Nation>
<Site>Omo Valley</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>18</UNESCO>
<Nation>ETH</Nation>
<Site>Lalibela</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>19</UNESCO>
<Nation>ETH</Nation>
<Site>Fasil Ghebbi</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>20</UNESCO>
<Nation>SYR</Nation>
<Site>Damascus</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>21</UNESCO>
<Nation>SYR</Nation>
<Site>Aleppo</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>22</UNESCO>
<Nation>SYR</Nation>
<Site>Bosra</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>23</UNESCO>
<Nation>SYR</Nation>
<Site>Palmyra</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>24</UNESCO>
<Nation>CAN</Nation>
<Site>Nahanni</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>25</UNESCO>
<Nation>SEN</Nation>
<Site>Djoudj</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>26</UNESCO>
<Nation>SEN</Nation>
<Site>Gorée</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>27</UNESCO>
<Nation>USA</Nation>
<Site>Mesa Verde</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>28</UNESCO>
<Nation>USA</Nation>
<Site>Yellowstone</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>28</UNESCO>
<Nation>USA</Nation>
<Site>Yellowstone NP</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>29</UNESCO>
<Nation>POL</Nation>
<Site>Krakow</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>30</UNESCO>
<Nation>POL</Nation>
<Site>Warszawa</Site>
<Seen>1</Seen>
</WHSite>
<WHSite>
<UNESCO>31</UNESCO>
<Nation>POL</Nation>
<Site>Oswiecim</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>32</UNESCO>
<Nation>POL</Nation>
<Site>Wieliczka</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>33</UNESCO>
<Nation>BLR</Nation>
<Site>Bialowieza Forest</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>33</UNESCO>
<Nation>POL</Nation>
<Site>Bialowieza Forest</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>34</UNESCO>
<Nation>GHA</Nation>
<Site>Accra</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>34</UNESCO>
<Nation>GHA</Nation>
<Site>Elmina</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>35</UNESCO>
<Nation>GHA</Nation>
<Site>Kumasi</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>36</UNESCO>
<Nation>TUN</Nation>
<Site>Tunis</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>37</UNESCO>
<Nation>TUN</Nation>
<Site>Carthage</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>38</UNESCO>
<Nation>TUN</Nation>
<Site>El Djem</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>39</UNESCO>
<Nation>TAN</Nation>
<Site>Ngorongoro</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>42</UNESCO>
<Nation>BUL</Nation>
<Site>Boyana</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>43</UNESCO>
<Nation>BUL</Nation>
<Site>Madara</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>44</UNESCO>
<Nation>BUL</Nation>
<Site>Kazanlak</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>45</UNESCO>
<Nation>BUL</Nation>
<Site>Ivanovo</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>55</UNESCO>
<Nation>NOR</Nation>
<Site>Røros</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>58</UNESCO>
<Nation>NOR</Nation>
<Site>Urnes</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>59</UNESCO>
<Nation>NOR</Nation>
<Site>Bergen</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>63</UNESCO>
<Nation>COD</Nation>
<Site>Virunga</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>64</UNESCO>
<Nation>GUA</Nation>
<Site>Tikal</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>65</UNESCO>
<Nation>GUA</Nation>
<Site>Antigua</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>71</UNESCO>
<Nation>CAN</Nation>
<Site>Dinosaur PP</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>72</UNESCO>
<Nation>CAN</Nation>
<Site>Kluane</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>72</UNESCO>
<Nation>CAN</Nation>
<Site>Tatshenshini-Alsek</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>72</UNESCO>
<Nation>USA</Nation>
<Site>Glacier Bay</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>72</UNESCO>
<Nation>USA</Nation>
<Site>Glacier Bay NP</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>72</UNESCO>
<Nation>USA</Nation>
<Site>Wrangell-St Elias</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>75</UNESCO>
<Nation>USA</Nation>
<Site>Grand Canyon</Site>
<Seen>1</Seen>
</WHSite>
<WHSite>
<UNESCO>76</UNESCO>
<Nation>USA</Nation>
<Site>Everglades</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>78</UNESCO>
<Nation>USA</Nation>
<Site>Philadelphia</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>79</UNESCO>
<Nation>CYP</Nation>
<Site>Paphos</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>80</UNESCO>
<Nation>FRA</Nation>
<Site>Mont St Michel</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>81</UNESCO>
<Nation>FRA</Nation>
<Site>Chartres</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>83</UNESCO>
<Nation>FRA</Nation>
<Site>Paris</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>84</UNESCO>
<Nation>FRA</Nation>
<Site>Vézelay</Site>
<Seen>1</Seen>
</WHSite>
<WHSite>
<UNESCO>85</UNESCO>
<Nation>FRA</Nation>
<Site>Vézère Valley</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>86</UNESCO>
<Nation>EGY</Nation>
<Site>Giza</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>86</UNESCO>
<Nation>EGY</Nation>
<Site>Memphis</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>87</UNESCO>
<Nation>EGY</Nation>
<Site>Karnak</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>87</UNESCO>
<Nation>EGY</Nation>
<Site>Luxor</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>87</UNESCO>
<Nation>EGY</Nation>
<Site>Thebes</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>88</UNESCO>
<Nation>EGY</Nation>
<Site>Abu Simbel</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>88</UNESCO>
<Nation>EGY</Nation>
<Site>Philae</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>89</UNESCO>
<Nation>EGY</Nation>
<Site>Cairo</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>90</UNESCO>
<Nation>EGY</Nation>
<Site>Abu Mena</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>91</UNESCO>
<Nation>ITA</Nation>
<Site>Roma</Site>
<Seen>1</Seen>
</WHSite>
<WHSite>
<UNESCO>93</UNESCO>
<Nation>ITA</Nation>
<Site>Milano</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>94</UNESCO>
<Nation>ITA</Nation>
<Site>Valcamonica</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>95</UNESCO>
<Nation>CRO</Nation>
<Site>Dubrovnik</Site>
<Seen>1</Seen>
</WHSite>
<WHSite>
<UNESCO>96</UNESCO>
<Nation>SRB</Nation>
<Site>Sopocani</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>96</UNESCO>
<Nation>SRB</Nation>
<Site>Stari Ras</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>97</UNESCO>
<Nation>CRO</Nation>
<Site>Split</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>98</UNESCO>
<Nation>CRO</Nation>
<Site>Plitvice Lakes</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>99</UNESCO>
<Nation>MKD</Nation>
<Site>Ohrid</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>100</UNESCO>
<Nation>MNE</Nation>
<Site>Durmitor</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>102</UNESCO>
<Nation>ALG</Nation>
<Site>Maadid</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>113</UNESCO>
<Nation>IRI</Nation>
<Site>Tchogha Zanbil</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>114</UNESCO>
<Nation>IRI</Nation>
<Site>Persepolis</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>115</UNESCO>
<Nation>IRI</Nation>
<Site>Isfahan</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>116</UNESCO>
<Nation>MLI</Nation>
<Site>Djenné</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>119</UNESCO>
<Nation>MLI</Nation>
<Site>Tombouctou</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>120</UNESCO>
<Nation>NEP</Nation>
<Site>Everest</Site>
<Seen>1</Seen>
</WHSite>
<WHSite>
<UNESCO>121</UNESCO>
<Nation>NEP</Nation>
<Site>Kathmandu</Site>
<Seen>1</Seen>
</WHSite>
<WHSite>
<UNESCO>124</UNESCO>
<Nation>BRA</Nation>
<Site>Ouro Preto</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>125</UNESCO>
<Nation>MNE</Nation>
<Site>Kotor</Site>
<Seen>1</Seen>
</WHSite>
<WHSite>
<UNESCO>129</UNESCO>
<Nation>HON</Nation>
<Site>Copan</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>130</UNESCO>
<Nation>MLT</Nation>
<Site>Hypogeum</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>131</UNESCO>
<Nation>MLT</Nation>
<Site>Valletta</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>132</UNESCO>
<Nation>MLT</Nation>
<Site>Malta</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>132</UNESCO>
<Nation>MLT</Nation>
<Site>Megalithic Temples</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>134</UNESCO>
<Nation>USA</Nation>
<Site>Redwood NP</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>135</UNESCO>
<Nation>PAN</Nation>
<Site>Portobelo-San Lorenzo</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>136</UNESCO>
<Nation>COD</Nation>
<Site>Garamba</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>137</UNESCO>
<Nation>COD</Nation>
<Site>Kahuzi-Biega</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>138</UNESCO>
<Nation>PAK</Nation>
<Site>Moenjodaro</Site>
<Seen>0</Seen>
</WHSite>
<WHSite>
<UNESCO>139</UNESCO>
<Nation>PAK</Nation>
<Site>Taxila</Site>
<Seen>0</Seen>
</WHSite>
